/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clima;

import static clima.Virtualizacion.readJsonFromUrl;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author joe
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Clima2
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID_Ciudad = new javax.swing.JTextField();
        LlaveAccesoClima = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NombreImagen = new javax.swing.JTextField();
        SubirImagen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RespuestaCancion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Obtener Cancion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Token Clima");

        jLabel2.setText("ID_Ciudad");

        jLabel3.setText("Nombre Imagen");

        NombreImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreImagenActionPerformed(evt);
            }
        });

        SubirImagen.setText("Subir Imagen");
        SubirImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirImagenActionPerformed(evt);
            }
        });

        RespuestaCancion.setColumns(20);
        RespuestaCancion.setRows(5);
        jScrollPane1.setViewportView(RespuestaCancion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LlaveAccesoClima, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addComponent(ID_Ciudad))
                            .addComponent(NombreImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(SubirImagen)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LlaveAccesoClima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(ID_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(NombreImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(SubirImagen))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String emocion;
    private String Clima;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       JSONObject json;
        try {
            
            json = readJsonFromUrl("http://18.222.26.10:3000/"+ID_Ciudad.getText()+"/"+LlaveAccesoClima.getText());
            System.out.println(json.get("dt_txt"));
            System.out.println(json.get("weather"));

            String clima[] = json.get("weather").toString().replace('\"', ' ').split(",");

            String Clima = (clima[2].split(":")[1].trim());
            json = readJsonFromUrl("http://18.222.26.10:3000/ciudad/"+ID_Ciudad.getText()+"/"+ LlaveAccesoClima.getText());

            System.out.println(json.toString());
            
            //JOptionPane.showMessageDialog(null, Clima ,"Clima" , JOptionPane.INFORMATION_MESSAGE);
            
            emocion = Virtualizacion.RespuestaURLRecognition("http://18.217.118.216:8000/", NombreImagen.getText());
            emocion = emocion.split(",")[0];
            //JOptionPane.showMessageDialog(null, emocion ,"Emocion" , JOptionPane.INFORMATION_MESSAGE);
             
            String respuesta = Virtualizacion.RespuestaURLSpotify("http://13.58.28.92:10000/", emocion.trim(), Clima);
            
            String res[] = respuesta.split(",");
            int contador = 0;
            int contador2 = 0;
            int bandera = 0;
            int bandera2 = 0;
            double duracionmin = 0;
            String nombreartista = "";
            String nombrealbum = "";
            String enlacepreview = "";
            String nombrecancion = "";
            String enlacecancion = "";
            for (int i = 0;i<res.length; i++){
            if (res[i].contains("name")){
            contador++;
            bandera = 1;
            }
            else{
            bandera = 0;
            }   
            if (res[i].contains("\"spotify\"")){
            contador2++;
            bandera2 = 1;
            }
            else{
            bandera2 = 0;
            }   
            if(contador == 1 && bandera == 1){
                String sp[] = res[i].split("\"");
                nombreartista = sp[3];    
            }
            else if(contador == 2 && bandera == 1){
                String sp[] = res[i].split("\"");
                nombrealbum = sp[3];
            }
            else if(contador == 4 && bandera == 1){
                String sp[] = res[i].split("\"");
                nombrecancion = sp[3];
            }

            if(contador2 == 4 && bandera2 == 1){
                String sp[] = res[i].split("\"");
                enlacecancion = sp[5];    
            }
            if (res[i].contains("duration_ms"))
            {
                 String sp[] = res[i].split(":");
                 String tr = sp[1].trim();
                 duracionmin = Math.round((Double.valueOf(tr)/(1000*60))*100)/100.0d;
            }
            if (res[i].contains("preview_url"))
            {
                String sp[] = res[i].split("\"");
                String tr = sp[3].trim();
                enlacepreview = tr;
            }
        }
            
            
            
            JOptionPane.showMessageDialog(null, "Nombre Artista: " +nombreartista+ "\n" + "Nombre Album: " +nombrealbum+ "\n" ,"Respuesta" , JOptionPane.INFORMATION_MESSAGE);
            
            //RespuestaCancion.setText("Nombre Artista: " +nombreartista+ "/n" + "Nombre Album: " +nombrealbum);
            Virtualizacion.goToURL(enlacepreview);
        } 
        
        
        catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } 

    }//GEN-LAST:event_jButton1ActionPerformed

    private void NombreImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreImagenActionPerformed

    private void SubirImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirImagenActionPerformed
                // TODO add your handling code here:
        SubirImagen ing = new SubirImagen();
        ing.setVisible(true);
                
    }//GEN-LAST:event_SubirImagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID_Ciudad;
    private javax.swing.JTextField LlaveAccesoClima;
    private javax.swing.JTextField NombreImagen;
    private javax.swing.JTextArea RespuestaCancion;
    private javax.swing.JButton SubirImagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
